"""
modules/astrometry/_wcs.py — Step 2: reading the WCS astap just solved (or
falling back to whatever WCS the FITS header itself already carries) and
validating it actually has celestial axes.

Internal helper only — not part of this package's public surface.
"""

from __future__ import annotations

import logging
import os

import astropy.io.fits as fits
from astropy.wcs import WCS

logger = logging.getLogger(__name__)


def _read_wcs(fits_path: str, output_base: str | None) -> tuple[WCS, int, int] | None:
    """
    Read the WCS for a just-solved frame, preferring astap's own fresh
    ``.wcs`` side file over whatever WCS keywords ``fits_path``'s own header
    may already carry.

    Real incident (2026-08-06, "UGC_6930" test frame): the incoming FITS
    already had CTYPE1/CRVAL1/CD* in its header (written by the capture
    software from mount pointing, per its own "Generated by INDI" comment —
    not a genuine plate solve). wcs.has_celestial was already True for THAT
    header, so the old code here never even looked at the .wcs file astap
    had just written — it silently kept using the mount-pointing estimate
    for every source's RA/Dec, Gaia zero-point, everything downstream.
    astap's own .wcs comment for that same run: "Solved in 0.1 sec. Offset
    3.0'. Mount offset RA=-0.2', DEC=-2.9'" — astap had already found and
    reported the ~178" correction; the old priority order just threw it
    away. By the time this is called, `_astap._run_astap()` has already
    confirmed ("Solution found" in astap_output) that this run's solve
    succeeded, so its own .wcs is the authoritative result — read it first,
    and only fall back to the FITS header's own WCS if that side file is
    missing or unexpectedly invalid.

    Returns
    -------
    tuple[WCS, int, int] | None
        (wcs, naxis1, naxis2) on success. None when the resulting WCS has no
        celestial axes at all — already logged in detail (the offending
        keywords found in the header, for diagnosis) before returning, so
        the caller (``solve()``) only needs to turn this into ``{}``.
    """
    fits_filename = os.path.basename(fits_path)

    wcs = None
    hdr = None
    naxis1: int = 0
    naxis2: int = 0

    with fits.open(fits_path) as hdul:
        hdr = hdul[0].header.copy()
        naxis1 = int(hdr.get("NAXIS1", 0))
        naxis2 = int(hdr.get("NAXIS2", 0))

    wcs_base = output_base if output_base else os.path.splitext(fits_path)[0]
    wcs_file_path = wcs_base + ".wcs"
    if os.path.exists(wcs_file_path):
        try:
            with fits.open(wcs_file_path) as wcs_hdul:
                wcs_hdr = wcs_hdul[0].header
                # astap writes BOTH CD* (correct, direct deg/px) AND
                # PC*+CDELT* into .wcs files. The PC values are NOT a
                # proper rotation matrix (det≈1) as the FITS standard
                # requires — they're just copies of the CD values.
                # When astropy sees both, pixel_scale_matrix computes
                # PC * diag(CDELT), double-applying the scale (real
                # incident 2026-08-06: 0.78"/px became 0.0002"/px,
                # making all FWHM values ≈0 and rejecting every source).
                # Fix: strip PC/CDELT when CD is present — CD is the
                # authoritative representation from astap's solver.
                if "CD1_1" in wcs_hdr:
                    for key in list(wcs_hdr.keys()):
                        if key.startswith("PC") or key.startswith("CDELT"):
                            del wcs_hdr[key]
                wcs_candidate = WCS(wcs_hdr)
                if wcs_candidate.has_celestial:
                    wcs = wcs_candidate
                    # Merge WCS keywords into main header for downstream use
                    for key in ["CTYPE1", "CTYPE2", "CRVAL1", "CRVAL2",
                                "CRPIX1", "CRPIX2", "CD1_1", "CD1_2",
                                "CD2_1", "CD2_2", "CDELT1", "CDELT2"]:
                        if key in wcs_hdr:
                            hdr[key] = wcs_hdr[key]
                else:
                    logger.warning(
                        "astap's .wcs file %s has no celestial axes — "
                        "falling back to fits_path's own header WCS",
                        wcs_file_path,
                    )
        except Exception as wcs_exc:
            logger.warning(
                "Failed to read astap's .wcs file %s: %s — falling back "
                "to fits_path's own header WCS",
                wcs_file_path,
                wcs_exc,
            )
    else:
        logger.warning(
            "astap's .wcs file not found at %s despite a reported "
            "solution — falling back to fits_path's own header WCS",
            wcs_file_path,
        )

    if wcs is None:
        # Fallback: whatever WCS (if any) fits_path's own header already
        # carries. May be a genuine prior plate solve, or may just be an
        # approximate mount-pointing estimate — see the incident above.
        with fits.open(fits_path) as hdul:
            wcs = WCS(hdul[0].header)
        if wcs.has_celestial:
            logger.warning(
                "Using fits_path's own header WCS as a fallback for %s — "
                "this was not verified against astap's own solve and may "
                "be no more than a mount-pointing estimate",
                fits_filename,
            )

    if not wcs.has_celestial:
        # Log detailed WCS info for debugging
        logger.error(
            "WCS has no celestial axes after plate solve for %s", fits_path
        )
        # Check for common WCS keywords to diagnose the issue
        wcs_keys = ["CTYPE1", "CTYPE2", "CRVAL1", "CRVAL2", "CRPIX1", "CRPIX2",
                    "CD1_1", "CD1_2", "CD2_1", "CD2_2", "CDELT1", "CDELT2"]
        found_keys = {k: hdr.get(k) for k in wcs_keys if k in hdr}
        logger.error(
            "WCS keywords found: %s  file=%s",
            found_keys if found_keys else "NONE",
            fits_filename,
        )
        # Also check if astap wrote solution info
        astap_keys = ["PLTSOLVD", "CRVAL1", "CRVAL2"]
        astap_found = {k: hdr.get(k) for k in astap_keys if k in hdr}
        logger.error(
            "ASTAP solution keywords: %s  file=%s",
            astap_found if astap_found else "NONE",
            fits_filename,
        )
        return None

    return wcs, naxis1, naxis2
